### PR TITLE
Export `typing.ForwardRef` subclass

### LINKED ISSUE #17: Export a `typing.ForwardRef` subclass
A convenient use case for providing a backport-supporting `typing.ForwardRef` subclass is when "stashing" info about type annotations in a way that allows to evaluate them later (within `_eval_direct` and not `typing.ForwardRef._evaluate`, if applicable) with a proper runtime evaluation strategy "smuggled in" implicitly.

Then, in libraries constructing `ForwardRef` from annotation strings manually, a snippet like this could be used to get the proper implementation of `ForwardRef`:

```py
try:
    from eval_type_backport import ForwardRef
except ImportError:
    from typing import ForwardRef

...
ann = ForwardRef("type[int] | None")
ann._evaluate(None, None)  # works on 3.8+
```

### PR DESCRIPTION
**Pull request by johnslavik**
Closes #17.

### CODE REVIEW

**Comment by alexmojaki** [comment]
Can you test `ForwardRef` inside `check_eval` and `check_subscript`?

**Comment by bswck** [comment]
Sure. Then I'll have to change these functions slightly to accept ready `ForwardRef` objects.

**Comment by bswck** [comment]
On the other hand, simply checking if `eval_type_backport.ForwardRef(...)._evaluate()` (caused by `typing._eval_type(eval_type_backport.ForwardRef(...))`) is less logically redundant.

@alexmojaki can I instead add an `eval_type_backport.eval_type_backport(eval_type_backport.ForwardRef())` test?
Or would you rather me to rewrite the entire test to check `eval_type_backport.ForwardRef` in every `check_eval` and `check_subscript` call?

**Comment by johnslavik** [comment]
Sure, makes more sense.

**Comment by johnslavik** [comment]
Ready for another round.

**Comment by johnslavik** [comment]
In https://github.com/alexmojaki/eval_type_backport/issues/17#issuecomment-2039741167, you said:
> so that backporting can just be 'turned on' and apply everywhere.

We can technically allow this by ensuring that replacing `typing.ForwardRef` with `eval_type_backport.ForwardRef` is possible in end-user code.
In order to do that, in `eval_type_backport.eval_type_backport`, we need to import `from typing` instead of importing `typing` and accessing `typing` members by attribute lookup.

Should I do that?

**Comment by alexmojaki** [comment]
I think the PR is pretty good as is. Please revert https://github.com/alexmojaki/eval_type_backport/pull/21/commits/44377ea9a21aff57321182336ba9bb2e590b2ce0 to fix the coverage, that extra check wasn't redundant since testing both kinds of refs in `check_eval` only works well in the happy path.

> We can technically allow this by ensuring that replacing `typing.ForwardRef` with `eval_type_backport.ForwardRef` is possible in end-user code.

I think it'd be better to replace `typing.ForwardRef._evaluate`, so that if someone does `from typing import ForwardRef` before the patching happens it will still work. Either way, that can be in the next PR.

**Comment by johnslavik** [comment]
> I think it'd be better to replace `typing.ForwardRef._evaluate`, so that if someone does `from typing import ForwardRef` before the patching happens it will still work. Either way, that can be in the next PR.

Very well said. Thanks!

**Comment by johnslavik** [comment]
Ready 🚀

**Comment by alexmojaki** [comment]
Thanks!

**Pull request merged**
